name: Deploy retype branch to server

on:
  push:
    branches: [ retype ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout retype branch
        uses: actions/checkout@v4
        with:
          ref: retype

      - name: Upload to server via SCP
        uses: appleboy/scp-action@master
        with:
          host: w01c4ca9.kasserver.com
          username: ssh-w02125c1
          key: ${{ secrets.SSH_KEY }}
          source: "./*"
          target: "/www/htdocs/w02125c1/website/retype"
          overwrite: true
